@startuml klassediagram

Abstract Class Account {
    -username: String
    -password: String
}

Class Administrator {
    -banUser()
    -deletPost()
}

Class User {
    -rating: float
    -suspended: boolean
    -blockedUsers: Array


    -blockUser()
    -reportUser()
    -rateuser(): void
    -postParkingspot(): void
    -deleteParkingspot(): void
}

Class Register {
    -users: ArrayList<Account>
    -parkingspots: ArrayList<ParkingSpot>

    -database: File
}

Class Post {
    -placesOfInterest: Array
    -description: String
    -fromTime: Time
    -toTime: Time
    -comments: ArrayList<String>
    -price: Float

    -addPost(): void
    -editPost(): void
}

Enum roadCondition {
    PRIVATE
    URBAN
}

Class Parkinglot {
    -name: String
    -id: Int
}

Class Parkingspot {
    -parkinglot: Parkinglot
    -owner: User
    -place: GeograficalPlace
    -type: roadCondition
    -widthInCentimeters: int
    -lengthInCentimeters: int
}

Class GeographicalPlace {
    -longitude: float
    -latitude: float
    -postalCode: String
    -city: String
    -streetAdress: String
    -streetNumber: String
}


roadCondition -- Parkingspot
Parkingspot -- Parkinglot
Post --|> Register
Register -- Parkingspot
Register -- Account
Account <|-- Administrator
Account <|-- User
Parkingspot -- GeographicalPlace

@enduml